### ISSUE TITLE
Title's like 'Runner2: Future Legend of Rhythm Alien, BIT.TRIP Presents… ' cause bytestrings errors in sqlite update

### ISSUE THREAD

**Issue by flyingclimber** [flyingclimber/Pagoda#2]
Runner2: Future Legend of Rhythm Alien, BIT.TRIP Presents�  { 9 } [ Microsoft Xbox Live Arcade ]
Traceback (most recent call last):
  File "./pagoda.py", line 146, in <module>
    db.update_score(src_game, src_platform, score)
  File "/Users/tfinc/Developer/Pagoda/database.py", line 64, in update_score
    (title, console, ign))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by flyingclimber** [comment]
"Viva Piñata: Trouble In Paradise" has the same issue
